const express=require('express'),http=require('http'),path=require('path'),fs=require('fs'),crypto=require('crypto'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),multer=require('multer');const{Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:true,credentials:true},maxHttpBufferSize:50*1024*1024});const PORT=+process.env.PORT||3000,HOST='0.0.0.0',SECRET=process.env.JWT_SECRET||crypto.randomBytes(32).toString('hex');const DATA=path.join(__dirname,'data'),UP=path.join(__dirname,'uploads');fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(UP,{recursive:true});const UF=path.join(DATA,'users.json'),MF=path.join(DATA,'messages.json');if(!fs.existsSync(UF))fs.writeFileSync(UF,'[]');if(!fs.existsSync(MF))fs.writeFileSync(MF,'[]');
const read=f=>{try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return[]}},write=(f,x)=>{const t=f+'.tmp';fs.writeFileSync(t,JSON.stringify(x,null,2));fs.renameSync(t,f)},safe=u=>({id:u.id,username:u.username,avatar:u.avatar||'',admin:!!u.admin,online:!!u.online}),tok=u=>jwt.sign({id:u.id},SECRET,{expiresIn:'30d'}),dec=t=>{try{return jwt.verify(t,SECRET)}catch{return null}};
const storage=multer.diskStorage({destination:(_r,_f,cb)=>cb(null,UP),filename:(_r,f,cb)=>cb(null,crypto.randomUUID()+path.extname(f.originalname).toLowerCase())});const upload=multer({storage,limits:{fileSize:25*1024*1024}});
app.use(express.json({limit:'2mb'}));app.use('/uploads',express.static(UP));app.use(express.static(path.join(__dirname,'public')));app.get('/api/health',(_r,s)=>s.json({ok:true}));
app.post('/api/register',async(req,res)=>{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');if(!/^[a-zA-Z0-9_]{3,24}$/.test(username))return res.status(400).json({error:'Username: 3-24 letters, numbers or underscore.'});if(password.length<6)return res.status(400).json({error:'Password must be at least 6 characters.'});const us=read(UF);if(us.some(u=>u.username.toLowerCase()===username.toLowerCase()))return res.status(409).json({error:'Username already exists.'});const u={id:crypto.randomUUID(),username,password:await bcrypt.hash(password,12),avatar:'',admin:us.length===0,online:false};us.push(u);write(UF,us);res.json({token:tok(u),user:safe(u)})});
app.post('/api/login',async(req,res)=>{const us=read(UF),u=us.find(x=>x.username.toLowerCase()===String(req.body.username||'').trim().toLowerCase());if(!u||!(await bcrypt.compare(String(req.body.password||''),u.password)))return res.status(401).json({error:'Wrong username or password.'});u.online=true;write(UF,us);res.json({token:tok(u),user:safe(u)})});
app.get('/api/me',(req,res)=>{const d=dec((req.headers.authorization||'').replace(/^Bearer\s+/i,'')),u=d&&read(UF).find(x=>x.id===d.id);u?res.json({user:safe(u)}):res.status(401).json({error:'Unauthorized'})});
app.get('/api/messages',(req,res)=>{if(!dec((req.headers.authorization||'').replace(/^Bearer\s+/i,'')))return res.status(401).json({error:'Unauthorized'});res.json({messages:read(MF).slice(-500)})});
app.post('/api/upload',upload.single('file'),(req,res)=>{if(!dec((req.headers.authorization||'').replace(/^Bearer\s+/i,''))){if(req.file)fs.unlinkSync(req.file.path);return res.status(401).json({error:'Unauthorized'})}if(!req.file)return res.status(400).json({error:'No file.'});res.json({name:req.file.originalname,size:req.file.size,mime:req.file.mimetype,url:'/uploads/'+req.file.filename})});
app.post('/api/avatar',upload.single('file'),(req,res)=>{const d=dec((req.headers.authorization||'').replace(/^Bearer\s+/i,''));if(!d||!req.file||!req.file.mimetype.startsWith('image/')){if(req.file)fs.unlinkSync(req.file.path);return res.status(400).json({error:'Image required.'})}const us=read(UF),u=us.find(x=>x.id===d.id);if(!u)return res.status(404).json({error:'User not found.'});u.avatar='/uploads/'+req.file.filename;write(UF,us);res.json({user:safe(u)})});
function su(s){return read(UF).find(u=>u.id===s.userId)}function leave(s){const r=s.data.room;if(r){s.to('voice:'+r).emit('voice:left',{id:s.id});s.leave('voice:'+r);s.data.room=null}}
io.use((s,n)=>{const d=dec(s.handshake.auth?.token);if(!d)return n(new Error('Unauthorized'));s.userId=d.id;n()});io.on('connection',s=>{const u=su(s);if(!u)return s.disconnect();u.online=true;write(UF,read(UF).map(x=>x.id===u.id?u:x));io.emit('presence',{user:safe(u),online:true});s.join('chat');
s.on('message:send',p=>{const u=su(s),text=String(p?.text||'').trim();if(!u||(!text&&!p?.url)||text.length>4000)return;const m={id:crypto.randomUUID(),userId:u.id,username:u.username,avatar:u.avatar||'',type:['text','file','image','audio'].includes(p.type)?p.type:'text',text,url:p.url||'',fileName:p.fileName||'',fileSize:+p.fileSize||0,mime:p.mime||'',replyTo:p.replyTo||null,edited:false,createdAt:Date.now()};const a=read(MF);a.push(m);write(MF,a.slice(-5000));io.to('chat').emit('message:new',m)});
s.on('message:edit',p=>{const u=su(s),a=read(MF),m=a.find(x=>x.id===p?.id);if(!u||!m||(m.userId!==u.id))return;m.text=String(p.text||'').trim().slice(0,4000);if(!m.text)return;m.edited=true;write(MF,a);io.to('chat').emit('message:updated',m)});
s.on('message:delete',p=>{const u=su(s),a=read(MF),i=a.findIndex(x=>x.id===p?.id);if(!u||i<0||(a[i].userId!==u.id&&!u.admin))return;const id=a[i].id;a.splice(i,1);write(MF,a);io.to('chat').emit('message:deleted',{id})});
s.on('admin:clear',()=>{if(su(s)?.admin){write(MF,[]);io.to('chat').emit('chat:cleared')}});
s.on('voice:join',room=>{leave(s);s.data.room=String(room||'General').slice(0,40);s.join('voice:'+s.data.room);s.to('voice:'+s.data.room).emit('voice:joined',{id:s.id,user:safe(su(s))})});s.on('voice:signal',p=>{if(p?.to)s.to(p.to).emit('voice:signal',{from:s.id,data:p.data})});s.on('voice:leave',()=>leave(s));s.on('disconnect',()=>{leave(s);const us=read(UF),x=us.find(q=>q.id===u.id);if(x){x.online=false;write(UF,us)}io.emit('presence',{user:safe(x||u),online:false})})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));server.listen(PORT,HOST,()=>console.log(`Dark Messenger: http://localhost:${PORT}`));
